### ISSUE TITLE
Auto kick chat being sent automatically even with option deactivated

### ISSUE THREAD

**Issue by munecito** [cssnr/playdrift-extension#23]
Hello.

The auto kick sends a notification to everyone in the room when someone is expelled.

The option to auto send is not selected.

Mozilla Firefox on Windows 11.

Release 0.4.10

**Comment by smashedr** [comment]
The option `Send Player Kicked Alert` was designed to send alerts when a player is kicked in a room you are in, but not the owner. That way you know if people are leaving the game, or if the room owner is kicking them. 

I never added an option to auto kick players silently for rooms that you are the owner of.

Is this a feature you would like to see implemented?

**Comment by munecito** [comment]
Oh sorry. I misunderstood the option. 

But yes it would be good if you could keep the auto kicks silent to the room. 

Thank you

**Comment by smashedr** [comment]
No problem, I see how the wording on that option can be confusing.

I will look at implementing this in the next version. Thank you for the feedback.

**Comment by smashedr** [comment]
I added this feature in PR #24 and released version 0.4.11:
https://github.com/cssnr/playdrift-extension/releases/tag/0.4.11

The release is available on Firefox now. Chrome usually publishes within 24 hours, but may take longer.
You can always download the signed chrome crx and drag it to your extensions page to install it asap:
https://github.com/cssnr/playdrift-extension/releases/download/0.4.11/playdrift_extension-chrome.crx

Let me know if you find any issues with this version and thanks for the feedback.

**Comment by munecito** [comment]
I'm on Firefox so it should be ok. 

I'll check in a little while. 

Thank you very much.

**Comment by munecito** [comment]
Everything seems to be working fine so far. 

Thank you for the newest release.

**Comment by smashedr** [comment]
That is great news, thanks for the confirmation. This is now also live on Chrome, so going to close this request out.

Feel free to open a new request for any issues you run into or features you would like to see, Thank you very much for the feedback and best of luck.
